package oscatalog

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/uplinkresearch/dsky/internal/appcatalog"
)

// Programs with Ubuntu (docs/plan-linux-apps.md, step 2).
//
// A plain Ubuntu entry writes Ubuntu's ISO as it is, and its installer asks
// everything. Picking programs turns it into an autoinstall: DSKY appends the
// answers (linux.autoinstall), and the installer puts the programs on.
//
// Three decisions shape the answers:
//   - Desktop keeps Ubuntu's own confirmation. The GRUB menu is left alone, so
//     the installer shows "Ready to install — Review your choices" with the
//     programs listed, and waits for Install before it erases the disk. Server
//     is hands-off.
//   - No account or password is in DSKY's answers. On Server the installer
//     asks for the account on screen (interactive identity); on Desktop,
//     Ubuntu's installer asks for it itself.
//   - Unofficial clients are not offered (see appcatalog.UbuntuSource).
//
// apt packages and snaps go in the installer's own sections. Flathub apps and
// Chrome, from Google's repository, install on first boot from a systemd
// service that waits for the network, logs to /var/log/dsky-apps.log, and
// tries again at the next boot if anything failed. That was step 1's lesson
// too: the installer installs snaps on first boot as well.

// ProgramsSupported reports whether picking programs is offered for this
// entry: Ubuntu's own installer, which takes autoinstall answers.
func (e Entry) ProgramsSupported() bool {
	if e.Family == Windows {
		return true
	}
	return e.Family == Linux && strings.HasPrefix(e.ID, "ubuntu-") && e.Kind() != ImageRaw
}

// AppTarget is the operating system the program picker resolves for.
func (e Entry) AppTarget() appcatalog.Target {
	if e.Family == Windows {
		return appcatalog.TargetWindows
	}
	return appcatalog.TargetUbuntu
}

// ubuntuDesktop reports whether this is Ubuntu's desktop installer, which
// keeps its confirmation screen.
func (e Entry) ubuntuDesktop() bool { return e.Group() != Server }

// CheckPrograms validates a program list for this entry before anything is
// downloaded.
func CheckPrograms(e Entry, ids []string) error { return checkPrograms(e, ids) }

func checkPrograms(e Entry, ids []string) error {
	if len(ids) == 0 {
		return nil
	}
	if !e.ProgramsSupported() {
		return fmt.Errorf("installing programs alongside %s is not supported — programs can be installed with Windows and with Ubuntu (Server 24.04 and 26.04, Desktop 26.04)", e.Name)
	}
	if e.Family == Windows {
		_, _, err := appcatalog.Resolve(ids)
		return err
	}
	_, err := appcatalog.ResolveUbuntu(ids)
	return err
}

// ubuntuUserDataFile is where the generated answers go in a workspace.
func ubuntuUserDataFile(recipeID string) string {
	return "templates/dsky-ubuntu-" + recipeID + ".yaml.tmpl"
}

// writeUbuntuUserData writes the autoinstall answers for a program list into
// the workspace and returns their workspace-relative path.
func writeUbuntuUserData(wsDir, recipeID string, e Entry, ids []string) (string, error) {
	plan, err := appcatalog.ResolveUbuntu(ids)
	if err != nil {
		return "", err
	}
	rel := ubuntuUserDataFile(recipeID)
	p := filepath.Join(wsDir, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return "", err
	}
	// The picker's choices go in as a comment, so the recipe can be opened
	// in the install dialog again: the answers alone only say what Ubuntu
	// installs, not which programs were picked.
	data := strings.Replace(ubuntuUserData(plan, e.ubuntuDesktop()), "\n", "\n"+programsMarker+strings.Join(ids, " ")+"\n", 1)
	return rel, os.WriteFile(p, []byte(data), 0o644)
}

// ubuntuUserData renders the cloud-config autoinstall answers. The output is
// also a Go template (compose renders user_data as one), so it must never
// contain "{{".
func ubuntuUserData(plan appcatalog.UbuntuPlan, desktop bool) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	w("#cloud-config")
	w("# Generated by DSKY. The programs picked in DSKY, for Ubuntu's installer.")
	w("autoinstall:")
	w("  version: 1")
	if !desktop {
		// No account in DSKY's answers: the installer asks for it on screen.
		w("  interactive-sections:")
		w("    - identity")
	}
	w("  storage:")
	w("    layout:")
	w("      name: direct")
	if len(plan.Apt) > 0 {
		w("  packages:")
		for _, p := range plan.Apt {
			w("    - %s", p)
		}
	}
	if len(plan.Snaps) > 0 {
		w("  snaps:")
		for _, s := range plan.Snaps {
			w("    - name: %s", s.Name)
			if s.Classic {
				w("      classic: true")
			}
		}
	}
	if plan.FirstBoot() {
		script := base64.StdEncoding.EncodeToString([]byte(ubuntuFirstBootScript(plan)))
		unit := base64.StdEncoding.EncodeToString([]byte(ubuntuFirstBootUnit))
		w("  late-commands:")
		w("    - mkdir -p /target/usr/local/sbin /target/etc/systemd/system")
		w("    - echo %s | base64 -d > /target/usr/local/sbin/dsky-apps.sh", script)
		w("    - chmod 0755 /target/usr/local/sbin/dsky-apps.sh")
		w("    - echo %s | base64 -d > /target/etc/systemd/system/dsky-apps.service", unit)
		w("    - curtin in-target --target=/target -- systemctl enable dsky-apps.service")
	}
	w("  shutdown: reboot")
	return b.String()
}

const ubuntuFirstBootUnit = `[Unit]
Description=DSKY: install the programs picked in DSKY
Wants=network-online.target
After=network-online.target
ConditionPathExists=!/var/lib/dsky/apps-done

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/dsky-apps.sh
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
`

// ubuntuFirstBootScript installs what the installer's sections can't: Flathub
// apps and vendor-repository packages. It runs until everything succeeds,
// once per boot, and one failure never stops the rest.
func ubuntuFirstBootScript(plan appcatalog.UbuntuPlan) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	w("#!/bin/bash")
	w("# Generated by DSKY. Installs the programs picked in DSKY that Ubuntu's")
	w("# installer can't: Flathub apps and vendor repositories. Log: /var/log/dsky-apps.log")
	w("exec >>/var/log/dsky-apps.log 2>&1")
	w(`note() { echo "$(date -Is) $*"; }`)
	w(`note "first-boot programs starting"`)
	w(`export DEBIAN_FRONTEND=noninteractive`)
	w(`for i in $(seq 1 90); do`)
	w(`  if timeout 10 bash -c '</dev/tcp/dl.google.com/443' 2>/dev/null; then break; fi`)
	w(`  [ "$i" = 1 ] && note "waiting for the network"`)
	w(`  sleep 10`)
	w(`done`)
	w(`failed=0`)
	w(`apt-get update -q || note "apt-get update failed"`)
	for _, repo := range plan.Repos {
		switch repo {
		case appcatalog.RepoGoogleChrome:
			w(`if dpkg -s google-chrome-stable >/dev/null 2>&1; then`)
			w(`  note "Google Chrome already installed"`)
			w(`elif [ "$(dpkg --print-architecture)" != amd64 ]; then`)
			w(`  note "SKIPPED Google Chrome: Google only publishes it for amd64"`)
			w(`else`)
			w(`  install -d -m 0755 /etc/apt/keyrings`)
			w(`  if apt-get install -y -q curl && curl -fsSL https://dl.google.com/linux/linux_signing_key.pub -o /etc/apt/keyrings/google-chrome.asc; then`)
			w(`    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.asc] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list`)
			w(`    if apt-get update -q && apt-get install -y -q google-chrome-stable; then note "installed Google Chrome"; else note "FAILED Google Chrome"; failed=1; fi`)
			w(`  else`)
			w(`    note "FAILED Google Chrome: could not fetch Google's signing key"; failed=1`)
			w(`  fi`)
			w(`fi`)
		}
	}
	if len(plan.Flatpaks) > 0 {
		w(`if ! command -v flatpak >/dev/null; then apt-get install -y -q flatpak || { note "FAILED installing flatpak"; failed=1; }; fi`)
		w(`if command -v flatpak >/dev/null; then`)
		w(`  flatpak remote-add --system --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo || { note "FAILED adding Flathub"; failed=1; }`)
		for _, id := range plan.Flatpaks {
			w(`  if flatpak install --system -y --noninteractive flathub %s; then note "installed %s"; else note "FAILED %s"; failed=1; fi`, id, id, id)
		}
		w(`fi`)
	}
	w(`if [ "$failed" = 0 ]; then`)
	w(`  mkdir -p /var/lib/dsky && touch /var/lib/dsky/apps-done`)
	w(`  note "first-boot programs done"`)
	w(`else`)
	w(`  note "first-boot programs finished with failures; trying again at the next boot"`)
	w(`fi`)
	w(`exit 0`)
	return b.String()
}
