package recipe

import (
	"fmt"
	"strings"
)

// AppsScope is the effective winget install scope for a spec.
func AppsScope(a *AppsSpec) string {
	if a != nil && a.Scope != "" {
		return a.Scope
	}
	return "machine"
}

// GenerateAppsPS renders the first-boot program installer: winget installs for
// every requested package, logged, best-effort, one failure never stopping the
// rest.
//
// Three things make this more than a one-line loop. App Installer (which
// provides winget) is a per-user MSIX and may still be registering when the
// first logon script runs, so winget is waited for rather than assumed.
// Packages download from the vendor, so the machine has to be online — the
// script waits for that too instead of failing fast on a NIC that is still
// coming up. And `--scope machine` is rejected outright by packages that only
// ship a per-user installer, so each one falls back to user scope rather than
// being skipped.
func GenerateAppsPS(r *Recipe) string {
	a := r.Windows.Apps
	scope := AppsScope(a)
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w(`# Generated by DSKY — recipe %s.`, r.ID)
	w(`# Installs programs with winget at first boot. Edit the recipe, not this file.`)
	w(`$ErrorActionPreference = 'Continue'`)
	w(`$log = Join-Path $PSScriptRoot 'apps.log'`)
	w(`function Note([string]$m) { "$(Get-Date -Format s) $m" | Add-Content -Path $log }`)
	w(`Note "app install starting (scope %s)"`, scope)
	w(``)
	w(`# App Installer is a per-user MSIX: right after the first logon it can`)
	w(`# still be registering, so winget may not resolve for a minute or two.`)
	w(`function Find-Winget {`)
	w(`  for ($i = 1; $i -le 30; $i++) {`)
	w(`    $c = Get-Command winget.exe -ErrorAction SilentlyContinue`)
	w(`    if ($c) { return $c.Source }`)
	w(`    $alias = Join-Path $env:LOCALAPPDATA 'Microsoft\WindowsApps\winget.exe'`)
	w(`    if (Test-Path $alias) { return $alias }`)
	w(`    if ($i -eq 1) { Note "waiting for winget (App Installer) to become available" }`)
	w(`    Start-Sleep -Seconds 10`)
	w(`  }`)
	w(`  return $null`)
	w(`}`)
	w(``)
	w(`# Packages come from the vendor, so this needs the network up. Microsoft's`)
	w(`# own connectivity-test endpoint is tiny and unauthenticated.`)
	w(`function Wait-Online {`)
	w(`  for ($i = 1; $i -le 30; $i++) {`)
	w(`    try {`)
	w(`      Invoke-WebRequest -Uri 'http://www.msftconnecttest.com/connecttest.txt' ` + "`")
	w(`        -UseBasicParsing -TimeoutSec 10 | Out-Null`)
	w(`      return $true`)
	w(`    } catch { }`)
	w(`    if ($i -eq 1) { Note "waiting for network" }`)
	w(`    Start-Sleep -Seconds 10`)
	w(`  }`)
	w(`  return $false`)
	w(`}`)
	w(``)
	w(`$wg = Find-Winget`)
	w(`if (-not $wg) {`)
	w(`  Note "FAILED winget never appeared — no programs installed."`)
	w(`  Note "  (Windows 10 images may need App Installer from the Store first.)"`)
	w(`  exit 0`)
	w(`}`)
	w(`Note "winget at $wg"`)
	w(`if (-not (Wait-Online)) { Note "WARNING no network; installs will likely fail" }`)
	w(``)
	w(`$apps = @(`)
	for _, id := range a.Winget {
		w(`  '%s',`, strings.ReplaceAll(id, "'", "''"))
	}
	w(`  $null`)
	w(`) | Where-Object { $_ }`)
	w(``)
	w(`$failed = @()`)
	w(`foreach ($id in $apps) {`)
	w(`  $base = @('install', '--id', $id, '--exact', '--silent',`)
	w(`            '--accept-package-agreements', '--accept-source-agreements',`)
	w(`            '--disable-interactivity')`)
	w(`  # Machine scope first where asked, then user scope: plenty of packages`)
	w(`  # ship only a per-user installer and refuse machine scope outright.`)
	w(`  $tries = @()`)
	if scope == "machine" {
		w(`  $tries += ,($base + @('--scope', 'machine'))`)
	}
	w(`  $tries += ,$base`)
	w(`  $tries += ,$base`)
	w(`  $ok = $false`)
	w(`  for ($t = 0; $t -lt $tries.Count; $t++) {`)
	w(`    if ($t -gt 0) { Start-Sleep -Seconds 15 }`)
	w(`    Note "installing $id (attempt $($t + 1))"`)
	w(`    & $wg $tries[$t] 2>&1 | Add-Content -Path $log`)
	w(`    $code = $LASTEXITCODE`)
	w(`    if ($code -eq 0) { $ok = $true; Note "installed $id"; break }`)
	w(`    # -1978335189 = already installed / no applicable upgrade.`)
	w(`    if ($code -eq -1978335189) { $ok = $true; Note "$id already present"; break }`)
	w(`    Note "$id attempt $($t + 1) exited $code"`)
	w(`  }`)
	w(`  if (-not $ok) { $failed += $id }`)
	w(`}`)
	w(``)
	w(`if ($failed.Count -gt 0) {`)
	w(`  Note "FAILED to install: $($failed -join ', ')"`)
	w(`} else {`)
	w(`  Note "all $($apps.Count) program(s) installed"`)
	w(`}`)
	w(`Note "app install done"`)
	return toCRLF(b.String())
}
