package recipe

import (
	"fmt"
	"strings"
)

// Consumer apps removed by preset. Names are Appx family-name prefixes
// matched with a trailing wildcard; the media itself is untouched so the
// result stays fully updatable and activation-safe.
var debloatStandardApps = []string{
	"Microsoft.BingNews",
	"Microsoft.BingWeather",
	"Microsoft.BingSearch",
	"Microsoft.GamingApp", // Xbox app
	"Microsoft.XboxGamingOverlay",
	"Microsoft.XboxGameOverlay",
	"Microsoft.XboxSpeechToTextOverlay",
	"Microsoft.Xbox.TCUI",
	"Microsoft.MicrosoftSolitaireCollection",
	"Microsoft.MicrosoftOfficeHub", // "Office" ad hub
	"Clipchamp.Clipchamp",
	"MicrosoftTeams",     // consumer Teams (11 21H2-22H2)
	"MSTeams",            // consumer Teams (23H2+)
	"Microsoft.Todos",
	"Microsoft.PowerAutomateDesktop",
	"MicrosoftCorporationII.MicrosoftFamily",
	"Microsoft.Getstarted", // Tips
	"Microsoft.WindowsFeedbackHub",
	"Microsoft.MixedReality.Portal",
	"Microsoft.Microsoft3DViewer",
	"Microsoft.SkypeApp",
	"Microsoft.Wallet",
}

// aggressive additionally removes apps some shops do use — review KeepApps
// before deploying.
var debloatAggressiveApps = []string{
	"Microsoft.OutlookForWindows", // new Outlook
	"Microsoft.YourPhone",         // Phone Link
	"MicrosoftWindows.CrossDevice",
	"Microsoft.WindowsMaps",
	"Microsoft.People",
	"Microsoft.GetHelp",
	"Microsoft.549981C3F5F10", // legacy Cortana
	"Microsoft.WindowsAlarms",
	"Microsoft.MicrosoftStickyNotes",
	"Microsoft.XboxIdentityProvider",
}

// DebloatApps returns the effective removal list for a spec.
func DebloatApps(d *DebloatSpec) []string {
	if !d.Enabled() {
		return nil
	}
	var apps []string
	apps = append(apps, debloatStandardApps...)
	if d.Preset == "aggressive" {
		apps = append(apps, debloatAggressiveApps...)
	}
	apps = append(apps, d.RemoveApps...)
	if len(d.KeepApps) == 0 {
		return apps
	}
	keep := map[string]bool{}
	for _, k := range d.KeepApps {
		keep[strings.ToLower(k)] = true
	}
	out := apps[:0]
	for _, a := range apps {
		if !keep[strings.ToLower(a)] {
			out = append(out, a)
		}
	}
	return out
}

// GenerateDebloatPS renders the first-boot PowerShell pass: provisioned and
// installed app removal plus policy keys for consumer content, ads,
// Copilot, widgets, and minimum telemetry. Everything is logged; every
// operation is best-effort so one missing app never aborts the install.
func GenerateDebloatPS(r *Recipe) string {
	d := r.Windows.Debloat
	apps := DebloatApps(d)
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w(`# Generated by The Composer — recipe %s, debloat preset %q.`, r.ID, d.Preset)
	w(`# Removes consumer apps and ad/telemetry surfaces at first boot; the`)
	w(`# installed media is official and untouched. Edit the recipe, not this file.`)
	w(`$ErrorActionPreference = 'Continue'`)
	w(`$log = Join-Path $PSScriptRoot 'debloat.log'`)
	w(`function Note([string]$m) { "$(Get-Date -Format s) $m" | Add-Content -Path $log }`)
	w(`Note "debloat starting (preset %s)"`, d.Preset)
	w(``)
	w(`$remove = @(`)
	for _, a := range apps {
		w(`  '%s',`, strings.ReplaceAll(a, "'", "''"))
	}
	w(`  $null`)
	w(`) | Where-Object { $_ }`)
	w(``)
	w(`$prov = Get-AppxProvisionedPackage -Online`)
	w(`$installed = Get-AppxPackage -AllUsers`)
	w(`foreach ($name in $remove) {`)
	w(`  foreach ($p in ($prov | Where-Object { $_.DisplayName -like "$name*" })) {`)
	w(`    try { Remove-AppxProvisionedPackage -Online -PackageName $p.PackageName | Out-Null; Note "deprovisioned $($p.DisplayName)" }`)
	w(`    catch { Note "FAILED deprovision $($p.DisplayName): $_" }`)
	w(`  }`)
	w(`  foreach ($p in ($installed | Where-Object { $_.Name -like "$name*" })) {`)
	w(`    try { Remove-AppxPackage -AllUsers -Package $p.PackageFullName; Note "removed $($p.Name)" }`)
	w(`    catch { Note "FAILED remove $($p.Name): $_" }`)
	w(`  }`)
	w(`}`)
	w(``)
	w(`function Set-Pol([string]$path, [string]$name, $value, [string]$type = 'DWord') {`)
	w(`  try {`)
	w(`    if (-not (Test-Path $path)) { New-Item -Path $path -Force | Out-Null }`)
	w(`    New-ItemProperty -Path $path -Name $name -Value $value -PropertyType $type -Force | Out-Null`)
	w(`    Note "set $path\$name = $value"`)
	w(`  } catch { Note "FAILED $path\${name}: $_" }`)
	w(`}`)
	w(``)
	w(`# Consumer promotions: suggested third-party apps, "fun facts", Start promos.`)
	w(`Set-Pol 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent' 'DisableWindowsConsumerFeatures' 1`)
	w(`Set-Pol 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent' 'DisableSoftLanding' 1`)
	w(`Set-Pol 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent' 'DisableCloudOptimizedContent' 1`)
	w(`# Copilot off (policy + this user's taskbar button).`)
	w(`Set-Pol 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot' 'TurnOffWindowsCopilot' 1`)
	w(`Set-Pol 'HKCU:\Software\Policies\Microsoft\Windows\WindowsCopilot' 'TurnOffWindowsCopilot' 1`)
	w(`Set-Pol 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced' 'ShowCopilotButton' 0`)
	w(`# Widgets / news-and-interests off.`)
	w(`Set-Pol 'HKLM:\SOFTWARE\Policies\Microsoft\Dsh' 'AllowNewsAndInterests' 0`)
	w(`Set-Pol 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced' 'TaskbarDa' 0`)
	w(`# Advertising ID and tailored experiences off.`)
	w(`Set-Pol 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\AdvertisingInfo' 'DisabledByGroupPolicy' 1`)
	w(`# Telemetry to the Pro floor (Required/Basic; 0 is Enterprise-only).`)
	w(`Set-Pol 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection' 'AllowTelemetry' 1`)
	w(`# Start/lock-screen suggestions and app promos for this user.`)
	w(`$cdm = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'`)
	w(`foreach ($v in 'SubscribedContent-338388Enabled','SubscribedContent-338389Enabled',`)
	w(`               'SubscribedContent-353694Enabled','SubscribedContent-353696Enabled',`)
	w(`               'SystemPaneSuggestionsEnabled','SilentInstalledAppsEnabled',`)
	w(`               'SoftLandingEnabled','RotatingLockScreenOverlayEnabled') {`)
	w(`  Set-Pol $cdm $v 0`)
	w(`}`)
	if d.Preset == "aggressive" {
		w(`# Aggressive: no web results in Start search.`)
		w(`Set-Pol 'HKCU:\Software\Policies\Microsoft\Windows\Explorer' 'DisableSearchBoxSuggestions' 1`)
	}
	w(``)
	w(`Note "debloat done"`)
	return toCRLF(b.String())
}