package recipe

import (
	"fmt"
	"regexp"
	"strings"
)

// Domain join by serial number: one stick for a batch of computers.
//
// An offline join file (`djoin /provision`) is one computer account, so it can
// join exactly one PC; putting one in the answer file makes one stick per PC.
// For a batch, the operator makes a file per computer named after that
// computer's serial number, and the stick carries all of them. During the
// specialize pass of Setup, before the first boot, DomainSerialScript reads the
// PC's serial number, applies the matching file with `djoin /requestodj`, and
// deletes every join file from the PC. The join takes effect at the reboot
// Setup does anyway, exactly when an answer-file join would, so the first-boot
// "did the join happen" check and verify.ps1 need nothing new.

// DomainSerialDir is where the join files are staged under Scripts\.
const DomainSerialDir = "dsky-domain"

// DomainSerialScriptName is the specialize-pass script under Scripts\. The
// unattend template names it, which is also how a template without the block
// is caught.
const DomainSerialScriptName = "dsky-domain-join.ps1"

// DomainSerialLog is the script's log under Scripts\.
const DomainSerialLog = "domain-join.log"

var serialKeyRe = regexp.MustCompile(`^[A-Z0-9][A-Z0-9._-]*$`)

// Placeholder serial numbers boards ship with. Every machine from that
// maker would share one, so a join file named after one would join them all as
// the same computer.
var placeholderSerials = map[string]bool{
	"0": true, "00000000": true, "0123456789": true, "1234567890": true, "NONE": true, "NA": true, "N/A": true,
	"DEFAULTSTRING": true, "TOBEFILLEDBYO.E.M.": true, "SYSTEMSERIALNUMBER": true,
	"CHASSISSERIALNUMBER": true, "INVALID": true, "NOTAPPLICABLE": true, "NOTSPECIFIED": true,
}

// SerialKey normalises a serial number the way the Setup script does:
// whitespace removed, upper case. It reports whether the result can name a
// join file for exactly one computer.
func SerialKey(serial string) (string, error) {
	key := strings.ToUpper(strings.Join(strings.Fields(serial), ""))
	switch {
	case key == "":
		return "", fmt.Errorf("empty serial number")
	case placeholderSerials[key]:
		return key, fmt.Errorf("%q is a placeholder serial number many computers share, not one computer's", serial)
	case !serialKeyRe.MatchString(key):
		return key, fmt.Errorf("%q is not a serial number (letters, digits, dot, dash or underscore)", serial)
	}
	return key, nil
}

// DomainSerialScript is the specialize-pass PowerShell. Parameters exist so
// tests can run it off Windows with a fake serial and a fake djoin.
const DomainSerialScript = `# Generated by DSKY. Joins this computer to the domain with the join file
# named after its serial number, then removes every join file from it.
param(
  [string]$Serial = "",
  [string]$Dir = "$env:WINDIR\Setup\Scripts\` + DomainSerialDir + `",
  [string]$Djoin = "$env:WINDIR\System32\djoin.exe",
  [string]$WindowsPath = "$env:WINDIR",
  [string]$Log = "$env:WINDIR\Setup\Scripts\` + DomainSerialLog + `"
)
function Note([string]$m) { "$(Get-Date -Format s) $m" | Add-Content -Path $Log }
$placeholders = @('0','00000000','0123456789','1234567890','NONE','NA','N/A','DEFAULTSTRING',
  'TOBEFILLEDBYO.E.M.','SYSTEMSERIALNUMBER','CHASSISSERIALNUMBER','INVALID','NOTAPPLICABLE','NOTSPECIFIED')
try {
  if (-not $Serial) { $Serial = [string](Get-CimInstance -ClassName Win32_BIOS).SerialNumber }
  $key = ($Serial -replace '\s', '').ToUpperInvariant()
  Note "serial number '$Serial', looking for $key.txt"
  $file = Join-Path $Dir "$key.txt"
  if (-not $key -or $placeholders -contains $key) {
    Note "NOT JOINED: this computer's serial number is empty or a placeholder, so no join file can be for it"
  } elseif (Test-Path -LiteralPath $file) {
    $out = & $Djoin /requestodj /loadfile $file /windowspath $WindowsPath /localos 2>&1
    $code = $LASTEXITCODE
    foreach ($l in $out) { if ("$l".Trim()) { Note "  djoin: $l" } }
    if ($code -eq 0) { Note "join file applied; the join completes when Setup restarts" }
    else { Note "NOT JOINED: djoin exited with $code" }
  } else {
    Note "NOT JOINED: no join file for serial number $key on this stick"
  }
} catch {
  Note "NOT JOINED: $($_.Exception.Message)"
} finally {
  # Every computer's join file was copied onto this disk, and each is that
  # computer's domain password. None of them stays.
  Remove-Item -LiteralPath $Dir -Recurse -Force -ErrorAction SilentlyContinue
  if (Test-Path -LiteralPath $Dir) { Note "WARNING: could not remove $Dir" } else { Note "join files removed from this computer" }
}
exit 0
`

// DomainSerialScriptFile is the script with Windows line endings.
func DomainSerialScriptFile() string { return toCRLF(DomainSerialScript) }
