package recipe

import (
	"encoding/xml"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Context is what templates see: {{.Org.Name}}, {{.Vars.admin_user}}, plus
// the recipe itself for advanced templates.
type Context struct {
	Org    OrgInfo
	Vars   map[string]string
	Recipe *Recipe
}

// OrgInfo identifies the workspace's organization (from workspace.yaml).
type OrgInfo struct {
	Name string
	ID   string
}

func xmlEscape(s string) string {
	var b strings.Builder
	_ = xml.EscapeText(&b, []byte(s))
	return b.String()
}

// RenderTemplate renders a workspace template file. Missing keys are errors:
// silently-empty unattend fields produce media that stalls at OOBE.
func RenderTemplate(path string, ctx Context) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	t, err := template.New(filepath.Base(path)).
		Funcs(template.FuncMap{"xml": xmlEscape}).
		Option("missingkey=error").
		Parse(string(b))
	if err != nil {
		return "", fmt.Errorf("template %s: %w", path, err)
	}
	var out strings.Builder
	if err := t.Execute(&out, ctx); err != nil {
		return "", fmt.Errorf("template %s: %w", path, err)
	}
	return out.String(), nil
}

// GenerateEICfg renders sources/ei.cfg (CRLF, as Windows media ships it).
func GenerateEICfg(e *EICfg) string {
	channel := e.Channel
	if channel == "" {
		channel = "Retail"
	}
	vl := "0"
	if e.VL {
		vl = "1"
	}
	return toCRLF(fmt.Sprintf("[EditionID]\n%s\n[Channel]\n%s\n[VL]\n%s\n", e.Edition, channel, vl))
}

// ResolvedDrivers is the driver material the `drivers` firstboot step
// installs, resolved by the compose stage to on-stick filenames.
type ResolvedDrivers struct {
	// Cabs are expand-then-sweep packs: the .cab filename staged directly
	// under Scripts/, expanded into Scripts/Drivers/<Dir>/ at boot.
	Cabs []struct {
		File string // e.g. intel-sst-10.29.0.12571.cab
		Dir  string // e.g. intel-sst
	}
	// Extracts are vendor self-extracting packs (Dell/Lenovo/HP): the exe
	// staged under Scripts/, unpacked into Scripts/Drivers/<Dir>/ at boot
	// with Args ({dir} substituted), then swept.
	Extracts []struct {
		File string
		Dir  string
		Args []string
	}
	// HasSweepable is true when any INF material lands under
	// Scripts/Drivers/ (inf-dir packs, expanded cabs, extracted packs).
	HasSweepable bool
	// Exes are vendor silent installers staged under Scripts/.
	Exes []struct {
		File string
		Args []string
		Log  string
	}
}

// GenerateFirstboot builds the first-boot .cmd from ordered steps —
// the generalized install-agent.cmd. resolveRef maps a payload/source ref to
// its staged filename under Scripts\.
func GenerateFirstboot(r *Recipe, drivers ResolvedDrivers, resolveRef func(ref string) (string, error)) (string, error) {
	w := r.Windows
	var b strings.Builder
	line := func(format string, args ...any) {
		fmt.Fprintf(&b, format+"\n", args...)
	}
	logNote := func(what string) {
		line(`echo [%%date%% %%time%%] %s exited with %%errorlevel%% >> "%%LOG%%"`, what)
	}

	line("@echo off")
	line("rem Generated by The Composer — recipe %s. Edit the recipe, not this file.", r.ID)
	line("setlocal")
	line(`set SCRIPTS=C:\Windows\Setup\Scripts`)
	line(`set LOG=%%SCRIPTS%%\%s`, w.Firstboot.Log)
	line("")
	line(`echo [%%date%% %%time%%] first-boot script starting >> "%%LOG%%"`)

	steps := w.Firstboot.Steps
	if len(steps) == 0 {
		steps = []Step{{Drivers: true}}
	}
	// A debloat spec without an explicit step runs right after drivers
	// (before agents, so their installs land on the cleaned system).
	if w.Debloat.Enabled() {
		has := false
		for _, s := range steps {
			if s.Debloat {
				has = true
			}
		}
		if !has {
			at := 0
			for i, s := range steps {
				if s.Drivers {
					at = i + 1
				}
			}
			steps = append(steps[:at:at], append([]Step{{Debloat: true}}, steps[at:]...)...)
		}
	}
	for _, s := range steps {
		line("")
		switch {
		case s.Drivers:
			for _, cab := range drivers.Cabs {
				line(`rem --- expand %s so the pnputil sweep below installs its drivers ---`, cab.File)
				line(`if exist "%%SCRIPTS%%\%s" (`, cab.File)
				line(`  mkdir "%%SCRIPTS%%\Drivers\%s" 2>nul`, cab.Dir)
				line(`  expand "%%SCRIPTS%%\%s" -F:* "%%SCRIPTS%%\Drivers\%s" > nul`, cab.File, cab.Dir)
				line(`  echo [%%date%% %%time%%] %s expand exited with %%errorlevel%% >> "%%LOG%%"`, cab.Dir)
				line(`)`)
			}
			for _, ex := range drivers.Extracts {
				dest := `%SCRIPTS%\Drivers\` + ex.Dir
				args := make([]string, len(ex.Args))
				for i, a := range ex.Args {
					args[i] = strings.ReplaceAll(a, "{dir}", dest)
				}
				line(`rem --- unpack vendor driver pack %s so the pnputil sweep installs it ---`, ex.File)
				line(`if exist "%%SCRIPTS%%\%s" (`, ex.File)
				line(`  mkdir "%s" 2>nul`, dest)
				line(`  "%%SCRIPTS%%\%s" %s`, ex.File, strings.Join(args, " "))
				line(`  echo [%%date%% %%time%%] %s extract exited with %%errorlevel%% >> "%%LOG%%"`, ex.Dir)
				line(`)`)
			}
			if drivers.HasSweepable {
				line(`rem --- pnputil installs only what matches this hardware, so packs for`)
				line(`rem --- multiple machine models can share one stick ---`)
				line(`if exist "%%SCRIPTS%%\Drivers\" (`)
				line(`  pnputil /add-driver "%%SCRIPTS%%\Drivers\*.inf" /subdirs /install >> "%%LOG%%" 2>&1`)
				line(`  echo [%%date%% %%time%%] pnputil exited with %%errorlevel%% >> "%%LOG%%"`)
				line(`)`)
			}
			for _, exe := range drivers.Exes {
				args := strings.Join(exe.Args, " ")
				if exe.Log != "" {
					args = strings.ReplaceAll(args, "{log}", `%SCRIPTS%\`+exe.Log)
				}
				line(`rem --- vendor driver installer %s ---`, exe.File)
				line(`if exist "%%SCRIPTS%%\%s" (`, exe.File)
				line(`  "%%SCRIPTS%%\%s" %s`, exe.File, args)
				line(`  echo [%%date%% %%time%%] %s exited with %%errorlevel%% >> "%%LOG%%"`, exe.File)
				line(`)`)
			}
		case s.Debloat:
			line(`rem --- debloat: strip consumer apps, ads, Copilot, widgets (preset %s) ---`, w.Debloat.Preset)
			line(`powershell -NoProfile -ExecutionPolicy Bypass -File "%%SCRIPTS%%\debloat.ps1" >> "%%LOG%%" 2>&1`)
			logNote("debloat")
		case s.Wait > 0:
			secs := int(s.Wait.Seconds())
			line(`rem --- settle for %ds (freshly-driver'd NICs need a moment before agents) ---`, secs)
			line(`ping -n %d 127.0.0.1 > nul`, secs+1)
		case s.MSI != nil:
			file, err := resolveRef(s.MSI.Ref)
			if err != nil {
				return "", err
			}
			logName := s.MSI.Log
			if logName == "" {
				logName = strings.TrimSuffix(file, filepath.Ext(file)) + "-msi.log"
			}
			line(`rem --- install %s ---`, file)
			args := strings.Join(s.MSI.Args, " ")
			if args == "" {
				args = "/qn"
			}
			line(`msiexec /i "%%SCRIPTS%%\%s" %s /l*v "%%SCRIPTS%%\%s"`, file, args, logName)
			logNote("msiexec")
		case s.Exe != nil:
			file, err := resolveRef(s.Exe.Ref)
			if err != nil {
				return "", err
			}
			line(`rem --- run %s ---`, file)
			line(`"%%SCRIPTS%%\%s" %s`, file, strings.Join(s.Exe.Args, " "))
			logNote(file)
		case s.Cmd != "":
			line("%s", s.Cmd)
		}
	}

	line("")
	line(`echo [%%date%% %%time%%] first-boot script done >> "%%LOG%%"`)
	line("endlocal")
	return toCRLF(b.String()), nil
}

// toCRLF normalizes to CRLF line endings — cmd.exe misparses LF-only batch
// files in several constructs, and ei.cfg ships CRLF on real media.
func toCRLF(s string) string {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	return strings.ReplaceAll(s, "\n", "\r\n")
}
