package recipe

import (
	"fmt"
	"strings"
)

// The post-install check.
//
// Everything this tool promises is decided at build time and delivered at
// first boot, with hours and a reinstall in between. Up to now the only way to
// know it worked was to look: Device Manager for yellow bangs, a Start menu
// for the programs, a domain login for the join. That is fine for one machine
// and useless for twenty, and it is exactly where a silent failure lives —
// nobody audits a machine that looks installed.
//
// So the build writes down what it intended, as a script that checks it. It is
// generated rather than shipped because only the build knows what was asked
// for, and it is PowerShell rather than a command in this tool because the
// machine it runs on has just been imaged and has nothing installed on it.
//
// Read-only. It reports and changes nothing, so running it twice, or on the
// wrong machine, costs nothing but the output.

// GenerateVerifyPS renders the post-install verification script.
//
// resolveRef maps a payload ref to its staged filename, the same as the
// first-boot generator, so a custom installer can be checked by the name it
// actually landed under.
func GenerateVerifyPS(r *Recipe, drivers ResolvedDrivers, resolveRef func(ref string) (string, error)) string {
	w := r.Windows
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p(`# Generated by The Uplink CompOSer - recipe %s.`, r.ID)
	p(`# Checks this machine against what the build intended. Read-only.`)
	p(`#`)
	p(`#   powershell -ExecutionPolicy Bypass -File C:\Windows\Setup\Scripts\verify.ps1`)
	p(`#`)
	p(`# Run it AFTER first boot has finished its work - installing programs takes`)
	p(`# a few minutes and needs the network. Run too early it exits 2 and says so.`)
	p(`#`)
	p(`# Exit codes:  0 matches the build   1 does not match   2 first boot still running`)
	p(``)
	p(`$ErrorActionPreference = 'SilentlyContinue'`)
	p(`$pass = 0; $fail = 0; $warn = 0`)
	p(`function OK   ($m) { $script:pass++; Write-Host ("  [ OK ] " + $m) -ForegroundColor Green }`)
	p(`function FAIL ($m) { $script:fail++; Write-Host ("  [FAIL] " + $m) -ForegroundColor Red }`)
	p(`function WARN ($m) { $script:warn++; Write-Host ("  [warn] " + $m) -ForegroundColor Yellow }`)
	p(`function Head ($m) { Write-Host ""; Write-Host $m -ForegroundColor Cyan }`)
	p(``)
	p(`Write-Host "Uplink post-install check - recipe %s" -ForegroundColor White`, r.ID)
	p(`Write-Host ("machine: " + $env:COMPUTERNAME + "   " + (Get-CimInstance Win32_ComputerSystem).Model)`)
	p(`$scripts = 'C:\Windows\Setup\Scripts'`)
	p(``)

	// ── First boot ───────────────────────────────────────────────────────
	// Everything else depends on this having run at all.
	p(`Head "First boot"`)
	p(`$fb = Join-Path $scripts '%s'`, firstbootLog(w))
	p(`if (Test-Path $fb) {`)
	p(`  $log = Get-Content $fb -Raw`)
	p(`  OK "first-boot script ran ($fb)"`)
	p(`  if ($log -match 'done') { OK "first-boot script reached the end" }`)
	p(`  else {`)
	// Told apart by how recently the log was touched. Installing programs
	// takes minutes and needs the network, so someone running this at the
	// first logon prompt would otherwise get a red report that only means
	// "not finished yet" — and a check that cries wolf gets ignored.
	p(`    $age = (Get-Date) - (Get-Item $fb).LastWriteTime`)
	p(`    if ($age.TotalMinutes -lt 10) {`)
	p(`      Write-Host ""`)
	p(`      Write-Host "  FIRST BOOT IS STILL RUNNING - checked too early." -ForegroundColor Yellow`)
	p(`      Write-Host ("  The log was written " + [int]$age.TotalSeconds + "s ago. Installing programs takes") -ForegroundColor Yellow`)
	p(`      Write-Host "  a few minutes and needs the network. Wait for it to finish, then run this again." -ForegroundColor Yellow`)
	p(`      Write-Host ("  Watch it:  Get-Content '" + $fb + "' -Wait") -ForegroundColor Yellow`)
	p(`      exit 2`)
	p(`    }`)
	p(`    FAIL ("first-boot log has no completion line and has not been written to for " + [int]$age.TotalMinutes + " minutes - it stopped partway")`)
	p(`  }`)
	// Nonzero exit codes are logged per step by the first-boot script.
	p(`  $bad = [regex]::Matches($log, '(?m)^.*exited with ([1-9]\d*)\s*$')`)
	p(`  if ($bad.Count -gt 0) { foreach ($m in $bad) { WARN ("a step reported failure: " + $m.Value.Trim()) } }`)
	p(`  else { OK "no step reported a nonzero exit code" }`)
	p(`} else { FAIL "no first-boot log at $fb - the script never ran" }`)
	p(``)

	// ── Drivers ──────────────────────────────────────────────────────────
	// The check that matters on a freshly imaged machine, and the one people
	// do by eye in Device Manager.
	p(`Head "Devices"`)
	p(`$prob = Get-CimInstance Win32_PnPEntity | Where-Object { $_.ConfigManagerErrorCode -ne 0 }`)
	p(`if ($prob) {`)
	p(`  FAIL ("" + $prob.Count + " device(s) have a problem:")`)
	p(`  foreach ($d in $prob) { Write-Host ("         " + $d.Name + "  [code " + $d.ConfigManagerErrorCode + "]  " + $d.DeviceID) }`)
	p(`} else { OK "every device has a working driver (no problem codes)" }`)
	// Vendor installers run as executables and leave no INF material, so they
	// are checked by their own logs; only sweepable packs land under Drivers/.
	if drivers.HasSweepable {
		p(`$staged = Join-Path $scripts 'Drivers'`)
		p(`if (Test-Path $staged) { OK ("driver material was staged: " + (Get-ChildItem $staged -Directory).Count + " pack(s) under Drivers\") }`)
		p(`else { WARN "no Drivers folder on the installed system - it may have been cleaned up after the sweep" }`)
	}
	for _, e := range drivers.Exes {
		log := e.Log
		if log == "" {
			log = strings.TrimSuffix(e.File, ".exe") + ".log"
		}
		p(`if (Test-Path (Join-Path $scripts '%s')) { OK "vendor driver installer %s ran (log present)" }`, log, e.File)
		p(`else { WARN "no log from vendor driver installer %s" }`, e.File)
	}
	p(``)

	// ── Account and edition ──────────────────────────────────────────────
	p(`Head "Windows"`)
	p(`$os = Get-CimInstance Win32_OperatingSystem`)
	p(`Write-Host ("         " + $os.Caption + " (" + $os.Version + ")")`)
	if w.EICfg != nil && w.EICfg.Edition != "" {
		p(`if ($os.Caption -match '%s') { OK "edition is %s as requested" }`, editionMatch(w.EICfg.Edition), w.EICfg.Edition)
		p(`else { FAIL "expected edition %s, got: $($os.Caption)" }`, w.EICfg.Edition)
	}
	if w.Unattend != nil {
		if user := w.Unattend.Vars["admin_user"]; user != "" && accountMode(w) == "local" {
			p(`if (Get-LocalUser -Name '%s' -ErrorAction SilentlyContinue) { OK "local account '%s' exists" }`, user, user)
			p(`else { FAIL "local account '%s' was not created" }`, user)
		}
	}
	p(``)

	// ── Domain ───────────────────────────────────────────────────────────
	// The silent one: Setup does not report a failed join, it just carries on.
	if w.Domain.Enabled() {
		p(`Head "Domain"`)
		p(`$cs = Get-CimInstance Win32_ComputerSystem`)
		p(`if ($cs.PartOfDomain) {`)
		if d := w.Domain; !d.Offline() && d.Join != "" && !strings.Contains(d.Join, "${var:") {
			p(`  if ($cs.Domain -eq '%s') { OK "joined %s" }`, d.Join, d.Join)
			p(`  else { FAIL ("joined the wrong domain: " + $cs.Domain + ", expected %s") }`, d.Join)
		} else {
			p(`  OK ("joined " + $cs.Domain)`)
		}
		// A join that succeeded but left a broken trust is the failure mode an
		// offline blob hits when something else renames the machine.
		p(`  if (Test-ComputerSecureChannel -ErrorAction SilentlyContinue) { OK "secure channel to the domain is healthy" }`)
		p(`  else { FAIL "domain trust relationship is broken - the machine name may not match its computer account" }`)
		p(`} else {`)
		p(`  FAIL ("NOT joined to a domain - this machine is in workgroup " + $cs.Workgroup)`)
		p(`  Write-Host "         Windows Setup does not report a failed join; it installs into a workgroup." -ForegroundColor Yellow`)
		p(`  foreach ($l in @('C:\DOMAIN-JOIN-FAILED-netsetup.log','C:\DOMAIN-JOIN-FAILED-setuperr.log','C:\DOMAIN-JOIN-FAILED-setupact.log')) {`)
		p(`    if (Test-Path $l) { Write-Host ("         evidence: " + $l) -ForegroundColor Yellow }`)
		p(`  }`)
		p(`}`)
		p(``)
	}

	// ── Programs ─────────────────────────────────────────────────────────
	if w.Apps.Enabled() || len(customInstallers(w, resolveRef)) > 0 {
		p(`Head "Programs"`)
		// One registry sweep, then match against it: querying winget per
		// package is slow and misses anything winget did not install.
		p(`$installed = @()`)
		p(`foreach ($k in @('HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',`)
		p(`                 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*',`)
		p(`                 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*')) {`)
		p(`  $installed += Get-ItemProperty $k | Where-Object { $_.DisplayName } | ForEach-Object { $_.DisplayName }`)
		p(`}`)
		p(`Write-Host ("         " + $installed.Count + " installed programs found")`)
		// Guarded: this block is also reached by a recipe that stages its own
		// installer and asks for no winget packages at all — which is the
		// ordinary MSP case, an agent and nothing else.
		if w.Apps.Enabled() {
			for _, pkg := range w.Apps.Winget {
				hint := wingetDisplayHint(pkg)
				p(`if ($installed -match '%s') { OK "%s is installed" } else { FAIL "%s is NOT installed" }`, hint, pkg, pkg)
			}
		}
		for _, c := range customInstallers(w, resolveRef) {
			p(`if (Test-Path (Join-Path $scripts '%s')) { OK "your installer %s was staged on the media" }`, c, c)
			p(`else { WARN "your installer %s is not in $scripts - it may have been cleaned up" }`, c)
		}
		p(`Write-Host "         (check any missing program in apps.log - winget needs the network at first boot)" -ForegroundColor DarkGray`)
		p(``)
	}

	p(`Head "Result"`)
	p(`Write-Host ("  passed $pass   failed $fail   warnings $warn")`)
	p(`if ($fail -gt 0) { Write-Host "  THIS MACHINE DOES NOT MATCH THE BUILD" -ForegroundColor Red; exit 1 }`)
	p(`Write-Host "  matches what the build intended" -ForegroundColor Green`)
	p(`exit 0`)
	return toCRLF(b.String())
}

// firstbootLog is the log name the first-boot script writes.
func firstbootLog(w *WindowsSpec) string {
	if w.Firstboot.Log != "" {
		return w.Firstboot.Log
	}
	return "firstboot.log"
}

func accountMode(w *WindowsSpec) string {
	if w.Unattend == nil {
		return ""
	}
	return w.Unattend.Vars["account_mode"]
}

// customInstallers lists the staged filenames of operator-supplied installers,
// so the check can confirm they reached the media.
func customInstallers(w *WindowsSpec, resolveRef func(string) (string, error)) []string {
	var out []string
	if resolveRef == nil {
		return out
	}
	for _, s := range w.Firstboot.Steps {
		for _, item := range []*RunItem{s.MSI, s.Exe} {
			if item == nil || item.Ref == "" {
				continue
			}
			if name, err := resolveRef(item.Ref); err == nil && name != "" {
				out = append(out, name)
			}
		}
	}
	return out
}

// editionMatch turns an ei.cfg EditionID into something Win32_OperatingSystem's
// Caption can be matched against ("Professional" reads as "Pro" there).
func editionMatch(edition string) string {
	switch edition {
	case "Professional":
		return "Pro"
	case "ProfessionalN":
		return "Pro N"
	case "Core":
		return "Home"
	}
	return edition
}

// wingetDisplayHint guesses the Add/Remove Programs name from a winget id.
// The publisher prefix is dropped and dots become spaces, which is close
// enough to match on — and a miss is reported as a failure to look at, not
// acted on.
func wingetDisplayHint(pkg string) string {
	name := pkg
	if i := strings.Index(pkg, "."); i >= 0 && i+1 < len(pkg) {
		name = pkg[i+1:]
	}
	name = strings.ReplaceAll(name, ".", " ")
	// Regex metacharacters would break the -match above.
	for _, ch := range []string{`\`, `(`, `)`, `[`, `]`, `+`, `*`, `?`, `^`, `$`, `|`, `{`, `}`} {
		name = strings.ReplaceAll(name, ch, `\`+ch)
	}
	return name
}
